# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"

[character]      # The name of the module we are configuring is "character"
symbol = "➜"     # The "symbol" segment is being set to "➜"
error_symbol = "✗"
use_symbol_for_status = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
style_root = "bold red"
style_user = "bold yellow"
disabled = false

[hostname]
ssh_only = false
prefix = "⟪"
suffix = "⟫"
disabled = false

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold cyan"
disabled = false
